# Generated by Django 4.0.4 on 2022-04-12 10:41

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registereduser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('phone', phone_field.models.PhoneField(help_text='business-registered phone number', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udhyog', models.CharField(max_length=12, unique=True)),
                ('pancard', models.CharField(max_length=10, unique=True)),
                ('adhaar', models.BigIntegerField(default=0, unique=True)),
                ('upi', models.CharField(max_length=45, unique=True)),
                ('ivrs', models.CharField(max_length=11, unique=True)),
                ('GST', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registereduser')),
            ],
        ),
    ]
