# Generated by Django 4.0.4 on 2022-04-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.PositiveBigIntegerField()),
                ('udhyog_id', models.PositiveBigIntegerField()),
                ('gst_no', models.CharField(max_length=15)),
                ('aadhar_no', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.PositiveBigIntegerField(help_text='business registered contact', unique=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('udhyog_id', models.PositiveBigIntegerField()),
                ('aadhar_no', models.PositiveBigIntegerField()),
                ('ivrs_no', models.CharField(help_text='property of business', max_length=11, unique=True)),
                ('gst_no', models.CharField(max_length=15)),
                ('upi_id', models.CharField(max_length=45, unique=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanITR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit', models.IntegerField()),
                ('gross_profit', models.IntegerField()),
                ('loans', models.IntegerField()),
                ('assets', models.IntegerField()),
                ('bankcsv', models.CharField(max_length=250)),
                ('pan_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.loggedinuser')),
            ],
        ),
        migrations.CreateModel(
            name='IvrsBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billcsv', models.CharField(max_length=254)),
                ('ivrs_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.loggedinuser')),
            ],
        ),
    ]
