# Generated by Django 4.0.4 on 2022-04-12 10:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='phone',
            field=phone_field.models.PhoneField(help_text='business-registered phone number', max_length=31),
        ),
    ]
